Hide default animation error on model creation
defold/extension-spine pull request #111
Opened 2022-12-07 10:44 UTC by SalavatR

2022-12-08 12:25 UTC, britzl commented
@SalavatR Thank you for the contribution. Is this PR connected to an open issue? If not, could you please provide a description of the PR and what it solves (more than what it says in the title)

2022-12-15 07:38 UTC, SalavatR commented
> @SalavatR Thank you for the contribution. Is this PR connected to an open issue? If not, could you please provide a description of the PR and what it solves (more than what it says in the title)

We have many spine models and run animations from code, extension spams to log `ERROR:SPINEEXT: No animation '' found`, on scene loading, i think it's not useful

2022-12-15 09:14 UTC, britzl commented
> We have many spine models and run animations from code, extension spams to log `ERROR:SPINEEXT: No animation '' found`, on scene loading, i think it's not useful

And this is because no animation was assigned to the spine scene in the editor?

2022-12-15 09:23 UTC, SalavatR commented
> > We have many spine models and run animations from code, extension spams to log `ERROR:SPINEEXT: No animation '' found`, on scene loading, i think it's not useful
> 
> And this is because no animation was assigned to the spine scene in the editor?

Yes)

2022-12-15 09:26 UTC, britzl commented
Hmm, ok, yeah, I mean if no animation has been set then I think it maybe makes sense to not try to play any animation and also not log a warning.

2022-12-15 13:18 UTC, SalavatR commented
> Hmm, ok, yeah, I mean if no animation has been set then I think it maybe makes sense to not try to play any animation and also not log a warning.

like this?
https://github.com/defold/extension-spine/blob/main/defold-spine/src/comp_spine_model.cpp#L588
if(animation_id != dmHashString64(""))
        {
            PlayAnimation(component, animation_id, dmGameObject::PLAYBACK_LOOP_FORWARD, 0.0f, 0.0f, 1.0f, 0); // TODO: Is the default playmode specified anywhere?
        }

2022-12-16 07:40 UTC, SalavatR commented
https://github.com/defold/extension-spine/issues/104#issue-1389256094 
here is issue :)

2022-12-18 14:02 UTC, britzl commented
> like this?

Well, I mean, now that I think of it there really should be no error/warning logged if the spine scene is created and the animation is empty. But I think using an empty hash later on should log a warning as that is likely indicative of an error.

I'd like to get some input from @JCash and/or @AGulev before we proceed.

2022-12-19 07:58 UTC, JCash commented
I do agree to removing the warning when starting the game (the build process should warn about it).
For the ingame setting of an empty string, I think it's still an error (what is the actual use case?)

2022-12-19 08:02 UTC, JCash requested changes

2022-12-19 08:02 UTC, JCash commented on defold-spine/src/comp_spine_model.cpp
> +        float blend_duration, float offset, float playback_rate, int track_index, bool is_initial = false)
We don't do default values (if we do, it's an oversight)

2022-12-19 08:02 UTC, JCash commented on defold-spine/src/comp_spine_model.cpp
> +        }
This code makes the code different from the gui code.

You should check if the `if (animationid)` before calling this function.

2022-12-19 08:02 UTC, JCash commented on defold-spine/src/comp_spine_model.cpp
> +        if (index == INVALID_ANIMATION_INDEX && is_initial && animation_id == dmHashString64(""))
For constant hashes we usually put them as constants at global scope, as you see at the top of the file.

Also, the hash of "" is 0.

2024-05-15 09:15 UTC, closed without merging